language: php

dist: trusty

php:
  - hhvm
  - nightly

matrix:
  fast_finish: true
  include:
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1

before_script:
  - travis_retry composer self-update
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml
