language: php

dist: trusty

php:
  - hhvm
  - nightly

matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.1
  allow_failures:
  - php: hhvm

before_script:
  - travis_retry composer self-update
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml
